import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "List of users",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body className={`${inter.className} antialiased body`}>
        <main className="py-16 max-w-[800px] mx-auto min-h-screen flex flex-col items-center space-y-8">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
